ajeldorado/falco-matlab

- config/falco_config_gen_chosen_pupil.m
- config/falco_init_ws.m
- lib/masks/segMirrorFunctions/hexSegMirror_getField.m
Allows the user the define static segment piston and tip/tilt errors for LUVOIR B
> LUVOIRB segmented primary phasing errors 

- lib/external/allcomb/allcomb.m
- lib/external/allcomb/license.txt
- lib/external/ini2struct/ini2struct.m
- lib/external/ini2struct/license.txt
- lib/external/struct2ini/license.txt
- lib/external/struct2ini/struct2ini.m
The external library functions are from the Mathworks File Exchange and are redistributable provided that their licenses and copyright statements are included with them.
> Added a folder of external library functions

- lib/masks/falco_gen_tradApodizer.m
- lib/masks/test_falco_gen_tradApodizer.m
Included a test script to demo the traditional apodizer function.
Also, tweaked the number of iterations used.
> Traditional apodizer updates

- lib/imaging/falco_get_gpct_sbp_image.m
- lib/masks/demo_gen_pupil_Simple.m
- lib/masks/falco_gen_pupil_Simple.m
- setup/falco_config_gen_chosen_pupil.m
Added functions to interface with GPCT and modeling its elliptical pupil.
> GPCT preparation 

- lib/masks/demo_gen_SW_mask.m
- lib/masks/demo_gen_pupil_iSAT.m
- lib/masks/falco_gen_SW_mask.m
- setup/falco_config_gen_chosen_pupil.m
Improved the software mask generator to allow for arbitrary clocking.
> Update to the software mask function

- config/EXAMPLE_defaults_VC_simple.m
- lib/utils/falco_compute_thput.m
- main/EXAMPLE_main_VC_model_mismatch.m
- models/model_compact.m
- models/model_compact_general.m
- models/model_full.m
- models/model_full_Fourier.m
- setup/falco_config_gen_FPM_SPLC.m
- setup/falco_config_gen_chosen_LS.m
- setup/falco_config_gen_chosen_apodizer.m
- setup/falco_config_gen_chosen_pupil.m
- setup/falco_init_ws.m
- Also fixed a matrix padding bug in the vortex compact model.
> Added example main script with model mismatch.

- falco_wfsc_loop.m
- lib/plot/falco_plot_progress.m
- main/EXAMPLE_main_WFIRST_HLC_design.m
- models/model_Jacobian.m
- models/model_Jacobian_HLC_scale.m
- models/model_compact.m
- models/model_compact_scale.m
- models/model_full.m
- setup/falco_config_gen_chosen_pupil.m
- setup/falco_init_ws.m
- However, CGI models will be added later once they are released.
> Added cases to allow WFIRST CGI models to run

- lib/external/subtightplot.m
- lib/imaging/falco_get_hcst_sbp_image.m
- lib/plot/falco_plot_progress_hcst.m
- lib/wfsc/falco_zwfs_reconstructor.m
Added subtightplot to help make less cumbersome figures. 
Added NKT source option to falco_get_hcst_sbp_image
> Testbed updates: hcst 

- falco_wfsc_loop.m
- lib/plot/falco_plot_pairwise_probes.m
- lib/wfsc/falco_est_pairwise_probing.m
- main/EXAMPLE_main_VC_model_mismatch.m
- Estimator plot was showing entire DM commands instead of just probe commands. It was also generating a new figure each iteration by accident.
- Moved system ID variables to main script. No longer hard coded.
> Bug fix in estimator plotting. Made system ID variables not hard-coded.

- lib/imaging/falco_get_expected_summed_image.m
- lib/wfsc/falco_ctrl_EFC_base.m
- setup/falco_init_ws.m
New option: added model-based grid search option for EFC. Set by the variable mp.ctrl.flagUseModel.
> New option: added model-based grid search option for EFC.

- .gitignore
- config/EXAMPLE_defaults_LUVOIRB_VC_design.m
- lib/dm/falco_discretize_dm_surf.m
- lib/imaging/falco_get_hcst_sbp_image.m
Modified testbed code to enable experimental demonstration of the LSB effect. 
Tweaked the LUVOIR B example to match the real thing.
> Mod for LSB demo on HCST && LUVOIRB example

- setup/falco_init_ws.m
- setup/falco_setup_FPM_HLC_cosine.m
- wfirst_modeling/EXAMPLE_defaults_WFIRST_PhaseB_PROPER_SPC_IFS_shear.m
- wfirst_modeling/EXAMPLE_defaults_WFIRST_PhaseB_SPC_IFS_simple_shear.m
- Added sheared pupil example for WFIRST CGI
> New example script. No changes to previous code.

- config/EXAMPLE_defaults_try_running_FALCO.m
- lib/dm/falco_fit_dm_surf.m
- lib/dm/falco_gen_dm_poke_cube.m
- lib/dm/propcustom_derotate_resize_dm_surface.m
- lib/external/arrayResize/arrayResize.m
- lib/external/arrayResize/license.txt
- lib/masks/falco_gen_annular_FPM.m
- lib/masks/falco_gen_bowtie_FPM.m
- lib/utils/falco_bin_downsample.m
- lib/utils/falco_rms.m
- models/model_Jacobian_HLC_scale.m
- models/model_compact_scale.m
- setup/falco_config_gen_FPM_LC.m
- setup/falco_config_gen_FPM_Roddier.m
- setup/falco_config_gen_chosen_LS.m
- setup/falco_config_gen_chosen_pupil.m
- setup/falco_init_ws.m
- wfirst_modeling/model_full_wfirst_phaseb.m
- Added some small functions. Minor edits to WFIRST models.
- New function to fit DM actuator commands to a surface of any resolution.
- Added if statements to mask generation functions. This allows someone to load their own masks without the mask generators tripping up. Not finished for all mask varieties.
- Fixed interpixel centering bug in influence function datacube generation.
> v3.2.1 Added some missing capabilities. Bug fixes

- lib/masks/demo_gen_pupil_LUVOIR_A_final.m
- lib/masks/falco_gen_pupil_LUVOIR_A_final.m
- lib/plot/falco_plot_superposed_pupil_masks.m
- setup/falco_gen_FPM_LC.m
Fixing minor bugs with pupil mask plotting function and LC mask generator.
> Minor bug fixes

- main/EXAMPLE_ZWFS_segErrors.m
- setup/falco_gen_FPM_Roddier.m
Added possibility to simulate a reflective ZWFS mask. 
Fixed bug in the example script.
> ZWFS: minor edits 

- lib/imaging/falco_get_Efield_cube.m
- lib/utils/fourierPixelate.m
- lib/utils/test_fourierPixelate.m
- lib/wfsc/falco_zwfs_getCalibrationImage.m
- lib/wfsc/falco_zwfs_getReferenceWave.m
- lib/wfsc/falco_zwfs_sim_image.m
- main/EXAMPLE_ZWFS_segErrors.m
- models/model_ZWFS.m
- Added new features to ZWFS code, included pixelated images 
- Added a function to simulate the E-field at the sub-bandpass centers using the full model
> ZWFS updates and new E-field cube function

- lib/plot/falco_plot_progress_dst.m
- lib/plot/falco_plot_progress_iact.m
- lib/wfsc/falco_ctrl_planned_EFC.m
- lib/wfsc/falco_drift_injection.m
- lib/wfsc/falco_est.m
- lib/wfsc/falco_est_ekf_maintenance.m
- lib/wfsc/falco_wfsc_loop.m
- lib/wfsc/initialize_ekf_maintenance.m
- main/EXAMPLE_main_dark_zone_maintenance.m
- setup/falco_verify_key_values.m
Dark zone maintenance code added.  Also updated some minor things to allow the code to run in simulation.  This branch has been tested in simulation with the iact config file.
> Dst sfr dzm

- lib/dm/falco_enforce_dm_constraints.m
- lib/dm/falco_gen_dm_surf.m
- lib/imaging/falco_get_sbp_image.m
- lib/imaging/falco_get_testbed_sbp_image.m
- lib/plot/falco_plot_superimposed_pupil_masks.m
- lib/wfsc/falco_ctrl_grid_search_EFC.m
- lib/wfsc/falco_ctrl_strategy_example.m
- lib/wfsc/falco_est_pairwise_probing.m
- models/model_compact.m
- models/model_compact_general.m
- setup/falco_set_optional_variables.m
Somehow a previous merge from the testbeds got rid of this feature.
> models: Add back sDebug variable into compact model

- lib/wfsc/falco_est.m
- lib/wfsc/falco_est_borde_traub_probing.m
- lib/wfsc/falco_est_pairwise_probing.m
- setup/falco_set_optional_variables.m
- setup/falco_verify_key_values.m
- Added Kalman filter to Borde-Traub estimator.
- Updated variable names in Kalman filter part of pairwise probing so that it will run again.
> Added Kalman filter to Borde-Traub estimator.

- lib/wfsc/falco_gen_pairwise_probe_square.m
- main/EXAMPLE_try_running_FALCO_fiber.m
Small change to 'probing-square' for the fiber case
> Fiber: probing fix 'probe-square'

- lib/masks/falco_gen_pupil_HWO2023_with_phase.m
- lib/masks/falco_gen_pupil_customHex.m
- lib/thinfilm/falco_thin_film_material_def.m
- lib/utils/fourierPixelate.m
- lib/wfsc/falco_zwfs_diff_reconstructor.m
- lib/wfsc/falco_zwfs_getCalibrationImage.m
- models/model_ZWFS.m
Added function to generate HWO hex pupil and segment level aberrations. Updated ZWFS modeling and reconstruction code with small bug fixes, and some features to enable the dual purpose mask model.
> HWO pupil, and ZWFS updates for DLPC work.

- lib/plot/falco_plot_superimposed_pupil_masks.m
- lib/utils/falco_compute_thput.m
- lib/wfsc/falco_ctrl_grid_search_EFC.m
Fixes issues 270-272 with one line change per each issue/commit.
> Fix270-272

- lib/wfsc/falco_est_ekf_maintenance.m
- main/EXAMPLE_main_dark_zone_maintenance.m
Updated DZM to repeat dither commands every N iterations. Also updated dither command to only be applied to the active elements. Also changed the control schedule array to automatically determine which dms are being used.
> DZM repeat dither commands
